python train.py --vocab_file ./mimicdata/mimic3/vocab.csv \
                --code_file ./mimicdata/mimic3/FULL_CODES.csv \
                --embed_file ./mimicdata/mimic3/processed_full.embed \
                --description_file ./mimicdata/mimic3/description_vectors.vocab \
                --train_file ./mimicdata/mimic3/train_FULL.csv \
                --dev_file ./mimicdata/mimic3/dev_FULL.csv \
                --test_file ./mimicdata/mimic3/test_FULL.csv \
                --save_dir mvc_full \
                --batch_size 4 \
                --gpus 0 \
                --epochs 100 \
                --lmbda 0 \
                --num_filter_maps 100 \
                --word_kernel_sizes 14,12,10,8 \
                --nw 0 \
                --lr 0.0001 \
                --log_frq 10 \
                --max_length 4000 \
                --method mvc
