python train.py --vocab_file ./mimicdata/mimic3/vocab.csv \
                --code_file ./mimicdata/mimic3/TOP_50_CODES.csv \
                --embed_file ./mimicdata/mimic3/processed_full.embed \
                --description_file ./mimicdata/mimic3/description_vectors.vocab \
                --train_file ./mimicdata/mimic3/train_50.csv \
                --dev_file ./mimicdata/mimic3/dev_50.csv \
                --test_file ./mimicdata/mimic3/test_50.csv \
                --save_dir multiscale-gcn \
                --batch_size 32 \
                --num_layers 6 \
                --drop_rate 0.0 \
                --gpus 2 \
                --epochs 200 \
                --lmbda 0 \
                --num_filter_maps 200 \
                --use_ontology 1 \
                --nw 4 \
                --lr 0.0001 \
                --log_frq 10 \
                --max_length 4000 \
                --method multiscale
