python train.py --vocab_file ./mimicdata/mimic3/vocab.csv \
                --code_file ./mimicdata/mimic3/TOP_50_CODES.csv \
                --embed_file ./mimicdata/mimic3/processed_full.embed \
                --description_file ./mimicdata/mimic3/description_vectors.vocab \
                --train_file ./mimicdata/mimic3/train_50.csv \
                --dev_file ./mimicdata/mimic3/dev_50.csv \
                --test_file ./mimicdata/mimic3/test_50.csv \
                --save_dir seq2seq \
                --batch_size 32 \
                --gpus 1 \
                --epochs 100 \
                --nw 0 \
                --lr 0.0001 \
                --log_frq 10 \
                --method seq2seq \
                --cell gru \
                --hidden_size 256 \
                --label_embed_size 150
